var listOfStages = [
  {"id": 0, "stagename": "stage1", "laststop": 0, "locked": 0, "done": 1},
  {"id": 1, "stagename": "stage2", "laststop": 0, "locked": 1, "done": 1},
  {"id": 2, "stagename": "stage3", "laststop": 0, "locked": 1, "done": 1},
  {"id": 3, "stagename": "stage4", "laststop": 0, "locked": 1, "done": 1},
  {"id": 4, "stagename": "stage5", "laststop": 0, "locked": 1, "done": 1},
  {"id": 5, "stagename": "stage6", "laststop": 0, "locked": 1, "done": 1},
  {"id": 6, "stagename": "stage7", "laststop": 0, "locked": 1, "done": 1},
  {"id": 7, "stagename": "stage8", "laststop": 0, "locked": 1, "done": 1},
  {"id": 8, "stagename": "stage9", "laststop": 0, "locked": 1, "done": 1},
  {"id": 9, "stagename": "stage10", "laststop": 0, "locked": 1, "done": 1},
  {"id": 10, "stagename": "stage11", "laststop": 0, "locked": 1, "done": 1},
  {"id": 11, "stagename": "stage12", "laststop": 0, "locked": 1, "done": 1},
  {"id": 12, "stagename": "stage13", "laststop": 0, "locked": 1, "done": 1},
  {"id": 13, "stagename": "stage14", "laststop": 0, "locked": 1, "done": 1},
  {"id": 14, "stagename": "stage15", "laststop": 0, "locked": 1, "done": 1},
  {"id": 15, "stagename": "stage16", "laststop": 0, "locked": 1, "done": 1},
  {"id": 16, "stagename": "stage17", "laststop": 0, "locked": 1, "done": 1},
  {"id": 17, "stagename": "stage18", "laststop": 0, "locked": 1, "done": 1},
  {"id": 18, "stagename": "stage19", "laststop": 0, "locked": 1, "done": 1},
  {"id": 19, "stagename": "stage20", "laststop": 0, "locked": 1, "done": 1},
];
